name: 'HarperDB Custom Functions Deployment Action'
description: 'Deploys the latest version of a Custom Functions package to a HarperDB Host'
inputs:
  admin_username:
    description: 'HarperDB Admin Username'
    required: true
  admin_password:
    description: 'HarperDB Admin Password'
    required: true
  hdb_endpoint:
    description: 'Where to deploy the Custom Functions to'
    required: true
  project_name:
    description: 'Which project to deploy the Custom Functions to'
    required: true
  cf_directory:
    description: 'Which directory the Custom Functions are contained within'
    required: true
  reject_unauthorized_certs:
    description: 'Whether or not to reject unauthorized certificates'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'